/**
 * Canadian tax constants, keyed by tax year.
 *
 * Every figure that indexes annually lives here so that a new tax year is a
 * data change, not a code change. Values are carried over verbatim from the
 * verified 2026 tables in the original planner.
 *
 * Sources: CRA indexation tables, taxtips.ca provincial rate tables, FSRA
 * (Ontario LIF maximums), ESDC quarterly CPP/OAS benefit amounts.
 */

import type { ProvinceKey } from "./types";

export interface Bracket {
  /** Upper bound of the bracket. Use Infinity for the top bracket. */
  up: number;
  /** Marginal rate as a fraction. */
  rate: number;
}

export interface Surtax {
  /** Provincial tax above this amount is surtaxed. */
  over: number;
  rate: number;
}

export interface ProvinceTax {
  name: string;
  brackets: Bracket[];
  surtax: Surtax[];
  /** Ontario levies a health premium on taxable income. */
  healthPremium: boolean;
  /** Basic personal amount. */
  bpa: number;
  /** Age amount (65+). */
  ageAmt: number;
  /** Net income at which the age amount begins to phase out. */
  ageThresh: number;
  /** Pension income amount. */
  penAmt: number;
  /** Dividend tax credit, as a fraction of the grossed-up eligible dividend. */
  divCredit: number;
  /**
   * Tax years in which this province's brackets and indexed non-refundable
   * personal credit amounts are frozen by statute (indexation paused).
   * Inclusive range; derived years inside it stay at the published values.
   */
  indexationPause?: { from: number; to: number };
}

export interface TaxYear {
  year: number;
  federal: Bracket[];
  provinces: Record<string, ProvinceTax>;

  /**
   * Batch 0D. Default annual indexation rate used to derive tax years beyond
   * the last published table. This is a PLANNING ASSUMPTION, not a published
   * CRA factor: the engine normally overrides it with the plan's inflation
   * assumption. Published years are never derived.
   */
  indexationRate: number;
  /**
   * Present only on a table generated by indexing an earlier published year.
   * Its value is the published year it was derived from. Absent = published.
   */
  derivedFrom?: number;


  /** Federal basic personal amount, maximum and floor, with its phase-out range. */
  fedBpaMax: number;
  fedBpaMin: number;
  fedBpaPhaseLo: number;
  fedBpaPhaseHi: number;

  fedAgeAmt: number;
  fedAgeThresh: number;
  /** Rate at which the age amount is clawed back. */
  agePhaseRate: number;
  fedPenAmt: number;
  /** Federal dividend tax credit, as a fraction of the grossed-up dividend. */
  fedDivCredit: number;
  /** Eligible dividend gross-up multiplier. */
  divGrossUp: number;

  /** OAS recovery-tax threshold. */
  oasThreshold: number;
  /** Annual OAS maximum, ages 65-74. */
  oasMax65: number;
  /** Annual OAS maximum, age 75+. */
  oasMax75: number;

  /** Annual CPP maximum at 65. */
  cppMax65: number;
  /** Average new CPP retirement pension taken at 65, annualized. */
  cppAvgNew65: number;
  /** Survivor's pension flat-rate portion, annualized (under 65). */
  cppSurvFlat: number;
  /** Maximum survivor's pension, under 65, annualized. */
  cppSurvMaxU65: number;
  /** Maximum survivor's pension, 65+, annualized. */
  cppSurvMax65: number;
  /** Maximum combined survivor + own retirement pension, annualized. */
  cppCombinedMax: number;
  /** One-time CPP death benefit. */
  cppDeathBenefit: number;

  /** Annual new TFSA room. */
  tfsaNewRoom: number;
  /** Annual RRSP dollar limit. */
  rrspLimit: number;
}

/* ------------------------------------------------------------------ */
/* 2026                                                                */
/* ------------------------------------------------------------------ */

const PROVINCES_2026: Record<string, ProvinceTax> = {
  ON: {
    name: "Ontario",
    brackets: [
      { up: 53891, rate: 0.0505 },
      { up: 107785, rate: 0.0915 },
      { up: 150000, rate: 0.1116 },
      { up: 220000, rate: 0.1216 },
      { up: Infinity, rate: 0.1316 },
    ],
    surtax: [
      { over: 5818, rate: 0.2 },
      { over: 7446, rate: 0.36 },
    ],
    healthPremium: true,
    // VERIFIED 2026-08-21 — CRA Form "TD1ON 2026 Ontario Personal Tax Credits
    // Return" (td1on-26e.pdf): basic personal amount $12,989 (line 1); age
    // amount $6,342 with the phase-out running from net income $47,210 to
    // $89,490 (line 2); pension income amount $1,796 (line 3). No value moved.
    bpa: 12989,
    ageAmt: 6342,
    ageThresh: 47210,
    penAmt: 1796,
    // VERIFIED 2026-08-21 — Ontario.ca, "Ontario dividend tax credit" (updated
    // 2026-04-27): 10.0% of the taxable (grossed-up) eligible dividend for
    // 2020-2026. Ontario carries no indexation pause.
    divCredit: 0.1,
  },
  BC: {
    name: "British Columbia",
    brackets: [
      { up: 50363, rate: 0.056 },
      { up: 100728, rate: 0.077 },
      { up: 115648, rate: 0.105 },
      { up: 140430, rate: 0.1229 },
      { up: 190405, rate: 0.147 },
      { up: 265545, rate: 0.168 },
      { up: Infinity, rate: 0.205 },
    ],
    surtax: [],
    healthPremium: false,
    // VERIFIED 2026-08-21 — Province of British Columbia, "B.C. basic personal
    // income tax credits" (last updated 2026-04-20).
    bpa: 13216,
    ageAmt: 5927,
    ageThresh: 44119,
    penAmt: 1000,
    divCredit: 0.12,
    // VERIFIED 2026-08-21 — Province of British Columbia, "Personal income tax
    // rates" (last updated 2026-04-17) / Budget 2026 tax measures: indexation
    // of BC brackets and non-refundable personal credits is PAUSED for tax
    // years 2027 through 2030, resuming in 2031.
    indexationPause: { from: 2027, to: 2030 },
  },
  AB: {
    name: "Alberta",
    brackets: [
      { up: 61200, rate: 0.08 },
      { up: 154259, rate: 0.1 },
      { up: 185111, rate: 0.12 },
      { up: 246813, rate: 0.13 },
      { up: 370220, rate: 0.14 },
      { up: Infinity, rate: 0.15 },
    ],
    surtax: [],
    healthPremium: false,
    bpa: 22769,
    // VERIFIED 2026-08-21 — CRA "TD1AB-WS Worksheet for the 2026 Alberta
    // Personal Tax Credits Return": age amount $6,345, phase-out beginning at
    // net income $47,234 (fully phased out at $89,534). Corrected on
    // 2026-08-21 from a stale 6055 / 45210.
    ageAmt: 6345,
    ageThresh: 47234,
    // VERIFIED 2026-08-21 — CRA Form "TD1AB 2026 Alberta Personal Tax Credits
    // Return" (td1ab-26e.pdf), line 3: Alberta pension income amount is the
    // lesser of $1,753 or the estimated annual pension. Corrected on
    // 2026-08-21 from a stale 1685 (the 2024 amount). Alberta's pension income
    // amount indexes (2024 1,685 -> 2025 1,719 -> 2026 1,753), so the generic
    // indexing of `penAmt` in derived years is correct behaviour for AB.
    penAmt: 1753,
    divCredit: 0.0812,
  },
  CUSTOM: {
    name: "Custom",
    brackets: [
      { up: 50000, rate: 0.1 },
      { up: Infinity, rate: 0.15 },
    ],
    surtax: [],
    healthPremium: false,
    bpa: 12000,
    ageAmt: 0,
    ageThresh: 9e9,
    penAmt: 0,
    divCredit: 0.1,
  },
};

export const TAX_2026: TaxYear = {
  year: 2026,
  federal: [
    { up: 58523, rate: 0.14 },
    { up: 117045, rate: 0.205 },
    { up: 181440, rate: 0.26 },
    { up: 258482, rate: 0.29 },
    { up: Infinity, rate: 0.33 },
  ],
  provinces: PROVINCES_2026,

  fedBpaMax: 16452,
  fedBpaMin: 14829,
  fedBpaPhaseLo: 181440,
  fedBpaPhaseHi: 258482,

  fedAgeAmt: 9208,
  fedAgeThresh: 46432,
  agePhaseRate: 0.15,
  fedPenAmt: 2000,
  fedDivCredit: 0.150198,
  divGrossUp: 1.38,

  oasThreshold: 95323,
  // July-September quarter maximums, annualized. 75+ receives 10% more.
  oasMax65: 9023.64,
  oasMax75: 9926.04,

  cppMax65: 18091.8, // $1,507.65/mo
  // VERIFIED 2026-08-21 against Canada.ca "CPP: How much you could receive"
  // (July-September 2026): $877.01/mo average new retirement pension at 65.
  // A statistic, not a statutory maximum; used only by the estimator.
  // Corrected from a stale 10,464 ($872/mo) on 2026-08-21.
  cppAvgNew65: 10524.12, // $877.01/mo x 12
  cppSurvFlat: 238.17 * 12,
  cppSurvMaxU65: 803.54 * 12,
  cppSurvMax65: 904.59 * 12,
  cppCombinedMax: 1531.56 * 12,
  cppDeathBenefit: 2500,

  tfsaNewRoom: 7000,
  rrspLimit: 33810,

  // Planning default only. Overridden by the plan's inflation assumption.
  indexationRate: 0.02,
};

const TAX_YEARS: Record<number, TaxYear> = {
  2026: TAX_2026,
};

/** The most recent tax year with published constants. */
export const LATEST_TAX_YEAR = 2026;

/** CRA rounds indexed statutory amounts to the nearest dollar. */
const idx = (v: number, f: number): number =>
  v === Infinity ? Infinity : Math.round(v * f);

function indexProvince(p: ProvinceTax, f: number): ProvinceTax {
  return {
    ...p,
    brackets: p.brackets.map((b) => ({ up: idx(b.up, f), rate: b.rate })),
    // Ontario's surtax thresholds are indexed annually along with the brackets.
    surtax: p.surtax.map((s) => ({ over: idx(s.over, f), rate: s.rate })),
    bpa: idx(p.bpa, f),
    ageAmt: idx(p.ageAmt, f),
    ageThresh: idx(p.ageThresh, f),
    penAmt: idx(p.penAmt, f),
  };
}

/**
 * Batch 0D — indexation (spec §12, Batch 0D).
 *
 * Derive a tax year beyond the last published table by indexing exactly the
 * amounts that index in law: the federal and provincial brackets and surtax
 * thresholds, the basic personal amounts, the age amount and its threshold,
 * the provincial pension income amounts, and the OAS recovery threshold.
 *
 * Deliberately NOT indexed here:
 *  - CPP/OAS benefit maximums — the projection already inflates benefit
 *    amounts through its own inflation factor; indexing them here as well
 *    would double-count.
 *  - `tfsaNewRoom` / `rrspLimit` — the room ledger (`room.ts`) indexes and
 *    rounds these itself, CRA-style, and flags them APPROXIMATE.
 *  - The Ontario Health Premium — its thresholds are fixed in statute and
 *    have not been indexed since 2004.
 *  - `fedPenAmt`, the federal pension income amount (line 31400) — a fixed
 *    $2,000 in ITA s.118(3), unchanged since 2006 and absent from CRA's
 *    indexation-adjustment tables (verified 2026-08-21). Provincial pension
 *    amounts DO index and are handled in `indexProvince`.
 *
 * Indexation is jurisdiction-aware: a province carrying an `indexationPause`
 * stays frozen at its published values for every year inside that range, and
 * afterwards resumes PROSPECTIVELY from the frozen amount — there is no
 * catch-up for the paused years.
 *
 * BC: paused 2027-2030 (Budget 2026), resuming 2031. Under BC Income Tax Act
 * s.4.52(2) each year's indexed amount is the immediately PRECEDING year's
 * amount plus that year's CPI adjustment, and s.4.52(4.25) suspends the
 * adjustment for 2027-2030. So 2030 still carries the 2026 amount and 2031
 * applies exactly ONE year's factor to it: base x (1+r), 2032 base x (1+r)^2.
 * (Current text of both provisions checked 2026-08-21.)
 */
export function provincialIndexationFactor(
  p: ProvinceTax,
  baseYear: number,
  year: number,
  rate: number,
): number {
  if (year <= baseYear) return 1;
  const pause = p.indexationPause;
  // Count the paused years falling in (baseYear, year] and drop them from the
  // exponent, generalised from the pause range rather than a fixed length.
  let paused = 0;
  if (pause) {
    const lo = Math.max(pause.from, baseYear + 1);
    const hi = Math.min(pause.to, year);
    if (hi >= lo) paused = hi - lo + 1;
  }
  const years = Math.max(0, year - baseYear - paused);
  return Math.pow(1 + rate, years);
}

export function indexTaxYear(base: TaxYear, year: number, rate: number): TaxYear {
  if (year <= base.year) return base;
  const f = Math.pow(1 + rate, year - base.year);
  const provinces: Record<string, ProvinceTax> = {};
  for (const [k, p] of Object.entries(base.provinces))
    provinces[k] = indexProvince(p, provincialIndexationFactor(p, base.year, year, rate));
  return {
    ...base,
    year,
    derivedFrom: base.year,
    indexationRate: rate,
    federal: base.federal.map((b) => ({ up: idx(b.up, f), rate: b.rate })),
    provinces,
    fedBpaMax: idx(base.fedBpaMax, f),
    fedBpaMin: idx(base.fedBpaMin, f),
    fedBpaPhaseLo: idx(base.fedBpaPhaseLo, f),
    fedBpaPhaseHi: idx(base.fedBpaPhaseHi, f),
    fedAgeAmt: idx(base.fedAgeAmt, f),
    fedAgeThresh: idx(base.fedAgeThresh, f),
    oasThreshold: idx(base.oasThreshold, f),
  };
}

const DERIVED_CACHE = new Map<string, TaxYear>();

/**
 * Look up a tax year's constants.
 *
 * Published years are returned exactly. Years beyond the last published table
 * are DERIVED by indexation (Batch 0D) rather than frozen at the last
 * published year, which used to make a flat-real income drift into higher
 * brackets over a 30-year projection. Derived years carry `derivedFrom`, so
 * callers can disclose that the table is indexed rather than published.
 */
export function getTaxYear(year: number, rate?: number): TaxYear {
  const published = TAX_YEARS[year];
  if (published) return published;
  const base = TAX_YEARS[LATEST_TAX_YEAR]!;
  if (year < LATEST_TAX_YEAR) return base;
  const r = rate ?? base.indexationRate;
  const key = `${year}:${r}`;
  const hit = DERIVED_CACHE.get(key);
  if (hit) return hit;
  const derived = indexTaxYear(base, year, r);
  DERIVED_CACHE.set(key, derived);
  return derived;
}

/** The factor by which statutory amounts are indexed between two years. */
export function indexationFactor(fromYear: number, toYear: number, rate: number): number {
  return toYear <= fromYear ? 1 : Math.pow(1 + rate, toYear - fromYear);
}


export function getProvince(taxYear: TaxYear, key: ProvinceKey): ProvinceTax {
  const p = taxYear.provinces[key];
  if (!p) throw new Error(`Unknown province "${key}" for tax year ${taxYear.year}`);
  return p;
}

/** Province keys with published tables, in display order. */
export function provinceKeys(taxYear: TaxYear): ProvinceKey[] {
  return Object.keys(taxYear.provinces) as ProvinceKey[];
}
